name: project_hostelite
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  icons_launcher: ^2.1.7
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  shared_preferences: ^2.2.3
  quickalert: ^1.1.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.5
  uuid: ^4.4.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7
  path: ^1.9.0
  url_launcher: ^6.3.0
  timeago: ^3.6.1
  intl: ^0.19.0
  internet_connection_checker_plus: ^2.4.2



icons_launcher:
  image_path: "assets/icons/hostelite-logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding_images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700